---

- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    
- name: disable SELinux on reboot
  selinux:
    state: disabled
    
- name: be sure firewalld is disabled
  systemd: name=firewalld enabled=no
  tags:
  - install
  - atomic
  - firewalld



- name: ensure private key and public one are present
  copy: 
    src: ~/.ssh 
    dest: "/root/" 
    mode: 0600
  with_items:
    - id_dsa.pub
    - id_dsa



- name: Set authorized key for user root copying it from current user
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"


- name: Install base
  yum: name=epel-release state=present

- name: create /data
  file:
    path: /data
    state: directory
    mode: 0777
# - name: Creating user codis with admin access
#   user: 
#     name: codis
#     password: {{ 11 | password_hash('sha512') }}
#     groups: wheel append=yes
#   when:  assigned_role  == "yes"

- name: Install App
  yum:
    name:
      - git
      - wget
      - net-tools
      - golang
      - sudo
      - mc
      - ntp
      - python-openshift
      - lvm2
      - nfs-utils



- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0


# - name: upgrade all packages
#   yum:
#     name: '*'
#     state: latest